spring:
  application:
    name: example

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j.timelimiter:
  configs:
    default:
      timeout-duration: 2s

resilience4j.retry:
  retry-aspect-order: 1
  metrics:
    legacy:
      enabled: true
    enabled: true
  instances:
    retryBackEndA:
      maxAttempts: 5
      waitDuration: 500ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    retryBackEndB:
      maxAttempts: 3
      waitDuration: 1s
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException

resilience4j.circuitbreaker:
  circuitbreaker-aspect-order: 2
  configs:
    forBackEndA:
      sliding-window-size: 3
      failure-rate-threshold: 50
      wait-duration-in-open-state: 15s
      minimum-number-of-calls: 5
      permitted-number-of-calls-in-half-open-state: 3
    forBackEndB:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 30s
      minimum-number-of-calls: 10
      permitted-number-of-calls-in-half-open-state: 5
  instances:
    backendA:
      baseConfig: forBackEndA
    backendB:
      baseConfig: forBackEndB
logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG
